Models/ErrorViewModel.cs
using System;

namespace Ewaste_Collection.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Ewaste.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ewaste_Collection.Models
{
    public class Ewaste
    {
        public int id { get; set; }

        public string  title { get; set; }
        public DateTime pickupdate { get; set; }
        public int quantity { get; set; }

        public double weight { get; set; }

        public int ecopoints { get; set; }

        public Ewaste()
        {

        }

    }
}

Controllers/EwasteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ewaste_Collection.Data;
using Ewaste_Collection.Models;
using Microsoft.AspNetCore.Authorization;

namespace Ewaste_Collection.Controllers
{
    public class EwasteController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EwasteController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ewastes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ewaste.ToListAsync());
        }

        // GET: Ewastes/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // GET: Ewastes/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index",await _context.Ewaste.Where(E=>E.title.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Ewastes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ewaste = await _context.Ewaste
                .FirstOrDefaultAsync(m => m.id == id);
            if (ewaste == null)
            {
                return NotFound();
            }

            return View(ewaste);
        }

        // GET: Ewastes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ewastes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,title,pickupdate,quantity,weight,ecopoints")] Ewaste ewaste)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ewaste);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ewaste);
        }

        // GET: Ewastes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ewaste = await _context.Ewaste.FindAsync(id);
            if (ewaste == null)
            {
                return NotFound();
            }
            return View(ewaste);
        }

        // POST: Ewastes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,title,pickupdate,quantity,weight,ecopoints")] Ewaste ewaste)
        {
            if (id != ewaste.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ewaste);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EwasteExists(ewaste.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ewaste);
        }

        // GET: Ewastes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ewaste = await _context.Ewaste
                .FirstOrDefaultAsync(m => m.id == id);
            if (ewaste == null)
            {
                return NotFound();
            }

            return View(ewaste);
        }

        // POST: Ewastes/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ewaste = await _context.Ewaste.FindAsync(id);
            _context.Ewaste.Remove(ewaste);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EwasteExists(int id)
        {
            return _context.Ewaste.Any(e => e.id == id);
        }
    }
}

Controllers/HomeController.cs
using Ewaste_Collection.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Ewaste_Collection.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Ewaste/Create.cshtml
@model Ewaste_Collection.Models.Ewaste

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ewaste</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pickupdate" class="control-label"></label>
                <input asp-for="pickupdate" class="form-control" />
                <span asp-validation-for="pickupdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="weight" class="control-label"></label>
                <input asp-for="weight" class="form-control" />
                <span asp-validation-for="weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ecopoints" class="control-label"></label>
                <input asp-for="ecopoints" class="form-control" />
                <span asp-validation-for="ecopoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ewaste/Delete.cshtml
@model Ewaste_Collection.Models.Ewaste

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ewaste</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pickupdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pickupdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ecopoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ecopoints)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Ewaste/Details.cshtml
@model Ewaste_Collection.Models.Ewaste

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ewaste</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pickupdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pickupdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ecopoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ecopoints)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Ewaste/Edit.cshtml
@model Ewaste_Collection.Models.Ewaste

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ewaste</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pickupdate" class="control-label"></label>
                <input asp-for="pickupdate" class="form-control" />
                <span asp-validation-for="pickupdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="weight" class="control-label"></label>
                <input asp-for="weight" class="form-control" />
                <span asp-validation-for="weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ecopoints" class="control-label"></label>
                <input asp-for="ecopoints" class="form-control" />
                <span asp-validation-for="ecopoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ewaste/Index.cshtml
@model IEnumerable<Ewaste_Collection.Models.Ewaste>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pickupdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ecopoints)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pickupdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ecopoints)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Ewaste/ShowSearchForm.cshtml
<h4>Search for Ewaste</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
               
            </div>
            
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ewaste_Collection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ewaste Collection</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ewaste" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ewaste" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ewaste_Collection - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>